//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportMasterTwo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FLQQVD1-ERAAP\\SQLEXPRESS;Initial Catalog=RMF;Integrated Security=True" +
            ";Pooling=False")]
        public string RMFConnectionString {
            get {
                return ((string)(this["RMFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Dsn=SOTAMAS90;uid=jt;description=MAS 90 4.0 ODBC Driver;directory=\\Er2\apps\Program Files\Sage Software\MAS 200\Version4\MAS90;prefix=\\Er2\apps\Program Files\Sage Software\MAS 200\Version4\MAS90\SY\, \\Er2\apps\Program Files\Sage Software\MAS 200\Version4\MAS90\==\;viewdll=\\Er2\apps\Program Files\Sage Software\MAS 200\Version4\MAS90\HOME;cachesize=4;dirtyreads=1;burstmode=1;striptrailingspaces=1;server=NotTheServer")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
    }
}
